#!/bin/sh

echo "CARAVEL_ROOT=$CARAVEL_ROOT"
echo "OPENLANE_ROOT=$OPENLANE_ROOT"
echo "OPENLANE_TAG=$OPENLANE_TAG"
echo "PDK_ROOT=$PDK_ROOT"
echo "PRECHECK_ROOT=$PRECHECK_ROOT"
echo "USE_ROOTLESS_DOCKER=$USE_ROOTLESS_DOCKER"

